INSERT INTO excuses (text) VALUES
    ('Sorry, I know I''m late'),
    ('It happens'),
    ('I was rescuing a squirrel'),
    ('Kids…'),
    ('I just wasn''t feeling it today'),
    ('I didn''t leave early enough'),
    ('There was too much traffic'),
    ('My car broke down'),
    ('I was stopped by the police'),
    ('My pet ran away'),
    ('My water pipes burst'),
    ('I felt very ill'),
    ('I lost my bag'),
    ('The weather was really bad'),
    ('I was held up at the doctor’s'),
    ('There''s been a death in the family'),
    ('My house got burgled'),
    ('I had a car accident'),
    ('It''s personal...'),
    ('I lost my car keys'),
    ('I lost my keys'),
    ('I stopped to help someone'),
    ('I had to drop off something at my grandma’s'),
    ('I had to go to the bank'),
    ('I got held up at the post office'),
    ('I couldn''t find my house key'),
    ('I started a small fire in my kitchen'),
    ('I fell down the stairs'),
    ('Sorry, I''m saving my energy for something I actually want to do'),
    ('I didn''t forget, I just chose not to remember'),
    ('I''m not ignoring you, I''m just giving you time to rethink that request'),
    ('Can’t. Won’t. Bye'),
    ('I''m allergic to effort'),
    ('My calendar says no'),
    ('Not in this economy'),
    ('The cat needs me'),
    ('I''m buffering'),
    ('My plants would miss me'),
    ('The stars aren’t aligned'),
    ('I''m in my villain era'),
    ('I''m in hibernation mode'),
    ('Can’t, I''m mid-plot twist'),
    ('Gravity’s extra strong today'),
    ('I''m currently unbothered. Do not disturb'),
    ('My alarm clock betrayed me'),
    ('I''m on airplane mode. Emotionally'),
    ('Lost a fight with my blanket'),
    ('My wifi and I are healing'),
    ('Error 404: motivation not found'),
    ('My pajamas wouldn’t let me leave'),
    ('My phone died'),
    ('I got stuck in a meeting'),
    ('The bus never showed up'),
    ('I overslept'),
    ('My train was cancelled'),
    ('I had a family emergency'),
    ('My babysitter cancelled'),
    ('I double-booked myself'),
    ('I got the time wrong'),
    ('I missed the email'),
    ('My laptop decided to update'),
    ('I was waiting for a delivery'),
    ('The neighbour’s dog escaped'),
    ('I got locked out'),
    ('My coffee machine broke'),
    ('I spilled coffee on everything'),
    ('My GPS sent me the wrong way'),
    ('I forgot what day it was'),
    ('Something came up'),
    ('Long story...'),
    ('I didn''t get the message'),
    ('My alarm didn''t go off'),
    ('I thought it was tomorrow'),
    ('I had a flat tyre'),
    ('I ran out of petrol'),
    ('I couldn''t find parking'),
    ('There was a strike'),
    ('The road was closed'),
    ('My internet was down'),
    ('There was a power cut'),
    ('I had a migraine'),
    ('I ate something bad'),
    ('I had a dentist appointment'),
    ('My kid was sick'),
    ('I was on the phone with my mum'),
    ('I had to wait for the plumber'),
    ('My boss kept me late'),
    ('I didn''t see the time'),
    ('It wasn''t me'),
    ('I missed my stop'),
    ('The lift was broken'),
    ('I got caught in the rain'),
    ('My umbrella broke'),
    ('I forgot my wallet'),
    ('I had to go back for my phone'),
    ('I left the stove on'),
    ('I had to go back and check I locked the door'),
    ('My shoe broke'),
    ('I tripped and hurt my ankle'),
    ('I had a sore throat'),
    ('I had a fever'),
    ('I couldn''t sleep last night'),
    ('I had a nightmare'),
    ('My back is killing me'),
    ('I pulled a muscle at the gym'),
    ('I had an allergic reaction'),
    ('I had to pick up my prescription'),
    ('My contact lens fell out'),
    ('I broke my glasses'),
    ('I had a job interview'),
    ('I had a parent-teacher meeting'),
    ('The school called'),
    ('I had to pick up the kids'),
    ('My child forgot their lunch'),
    ('The nanny was late'),
    ('My partner took the car'),
    ('My lift never showed up'),
    ('My taxi cancelled on me'),
    ('I got on the wrong train'),
    ('The metro was stuck in a tunnel'),
    ('There was an accident on the motorway'),
    ('There were roadworks everywhere'),
    ('I got lost'),
    ('My bike got a puncture'),
    ('Someone stole my bike'),
    ('Someone was parked in front of my garage'),
    ('My car wouldn’t start'),
    ('I had to sort out a parking ticket'),
    ('I had to renew my passport'),
    ('I was stuck in a queue'),
    ('The shop was packed'),
    ('I was waiting for a call back'),
    ('I was on hold for an hour'),
    ('My computer crashed'),
    ('I lost all my work'),
    ('I forgot to save'),
    ('The file got corrupted'),
    ('The printer jammed'),
    ('My password expired'),
    ('My account got locked'),
    ('I didn''t have signal'),
    ('My phone fell in the toilet'),
    ('My screen cracked'),
    ('I accidentally muted the chat'),
    ('It went to spam'),
    ('I thought I replied'),
    ('I wrote it down wrong'),
    ('I mixed up the dates'),
    ('I got the address wrong'),
    ('I went to the wrong place'),
    ('I misread the invitation'),
    ('Nobody told me'),
    ('I thought it was cancelled'),
    ('I was told it started later'),
    ('I had a deadline'),
    ('I had too much on my plate'),
    ('I was swamped'),
    ('I had to cover for a colleague'),
    ('I had a last-minute call'),
    ('I was on a work trip'),
    ('I was jet-lagged'),
    ('My flight was delayed'),
    ('I missed my connection'),
    ('My luggage got lost'),
    ('I had guests over'),
    ('I was looking after my neighbour’s cat'),
    ('The vet appointment ran late'),
    ('My cat was sick'),
    ('I had to walk the dog'),
    ('My landlord came round'),
    ('The heating broke'),
    ('There was a leak in the bathroom'),
    ('The washing machine flooded the kitchen'),
    ('I had to wait for the electrician'),
    ('I was moving house'),
    ('I was painting the flat'),
    ('I had to babysit'),
    ('It was my friend’s birthday'),
    ('I had a wedding to go to'),
    ('I was helping a friend move'),
    ('A friend needed me'),
    ('I was having a bad day'),
    ('I needed a mental health day'),
    ('I just needed some rest'),
    ('I had to finish something first'),
    ('I fell asleep on the sofa'),
    ('I got distracted'),
    ('I forgot'),
    ('I have no excuse'),
    ('I missed my stop because the podcast got good'),
    ('The lift was broken and my legs had opinions'),
    ('I got caught in the rain and had to dry off with dignity'),
    ('My umbrella turned inside out and so did my mood'),
    ('I forgot my wallet and only noticed at the till'),
    ('I had to go back for my phone, obviously'),
    ('I couldn''t remember if I turned the stove off'),
    ('I went back three times to check I locked the door'),
    ('My shoe gave up before I did'),
    ('I tripped on nothing and needed a minute'),
    ('My voice has left the building'),
    ('I had a fever and a dramatic blanket situation'),
    ('I slept like a toddler before Christmas'),
    ('I had a nightmare about being late, then I was'),
    ('My back has started making noises'),
    ('I went to the gym once and now I can’t walk'),
    ('I''m allergic to something and we’re still figuring out what'),
    ('The pharmacy queue was a lifestyle'),
    ('My contact lens is somewhere, just not in my eye'),
    ('I sat on my glasses'),
    ('I had a job interview, please act normal'),
    ('A teacher wanted to talk about my child’s “energy”'),
    ('The school called, and it''s never good news'),
    ('I had to pick up the kids and negotiate a snack treaty'),
    ('My child forgot their lunch and their shoes'),
    ('The nanny was late, so I was late, it''s a chain reaction'),
    ('My partner took the car without consulting me'),
    ('My lift said five minutes forty minutes ago'),
    ('My taxi saw me and kept driving'),
    ('I got on the right train going the wrong way'),
    ('The metro paused in a tunnel to think about life'),
    ('The motorway was a car park'),
    ('There are roadworks on every road I know'),
    ('My sense of direction is a work in progress'),
    ('My bike got a puncture, as is tradition'),
    ('Someone stole my bike, but left the lock'),
    ('Someone parked like they owned my garage'),
    ('My car needed a pep talk before starting'),
    ('I was arguing with a parking meter'),
    ('I was taking a passport photo, it took several attempts'),
    ('I picked the slowest queue, as always'),
    ('Everyone in town had the same errand as me'),
    ('They said they’d call back. They lied'),
    ('I was on hold and now I know the music by heart'),
    ('My computer crashed out of spite'),
    ('I lost all my work and some of my will to live'),
    ('I forgot to save, I live dangerously'),
    ('The file opened as pure gibberish'),
    ('The printer sensed I was in a hurry'),
    ('My password expired and I can’t reuse any of my favourites'),
    ('I got locked out of my account for being too sure of my password'),
    ('My phone had one bar and it was decorative'),
    ('My phone took a swim'),
    ('My screen cracked and I can only see half the messages'),
    ('I muted the group chat for peace and got too much peace'),
    ('Your email went to spam, take it up with the algorithm'),
    ('I replied in my head'),
    ('I wrote it down on a receipt I threw away'),
    ('I was confidently wrong about the date'),
    ('I went to the right street in the wrong town'),
    ('I went to the wrong place and waited patiently'),
    ('I read the invitation, just not very well'),
    ('Nobody told me, and I choose to believe that'),
    ('I assumed it was cancelled because I wanted it to be'),
    ('Someone told me it started later and I trusted them'),
    ('I had a deadline that was very much alive'),
    ('My plate is full and there’s no more room for dessert'),
    ('My to-do list has a to-do list'),
    ('I was covering for a colleague who is now in my debt'),
    ('A quick call turned into a long call'),
    ('I was on a work trip, mostly in airports'),
    ('My body is still in a different time zone'),
    ('My flight was delayed, then delayed again, for variety'),
    ('I missed my connection by one escalator'),
    ('My suitcase is having its own holiday'),
    ('I had guests and they didn''t take the hint'),
    ('I was cat-sitting and the cat was in charge'),
    ('The vet was running late, so was the dog'),
    ('My cat was sick on my shoes specifically'),
    ('The dog refused to come back from the walk'),
    ('My landlord dropped by unannounced, as usual'),
    ('The heating broke and I''m now a penguin'),
    ('My bathroom has become a water feature'),
    ('The washing machine tried to escape'),
    ('The electrician said morning, he meant evening'),
    ('I was moving house and now I live in boxes'),
    ('I was painting and now I am partly beige'),
    ('I was babysitting and lost the negotiation'),
    ('It was my friend’s birthday and the cake had a lot of layers'),
    ('I was at a wedding and the speeches ran long'),
    ('I was helping a friend move a sofa up four floors'),
    ('A friend needed me, and snacks'),
    ('My day was having a bad day'),
    ('I took a mental health day and it went well, thanks'),
    ('My body requested a day off and I approved it'),
    ('I had to finish something, then something else'),
    ('I sat on the sofa for one minute, which became three hours'),
    ('I got distracted by something shiny'),
    ('I forgot, but in a charming way'),
    ('I have no excuse, but I do have a smile'),
    ('It works on my machine'),
    ('It''s not a bug, it''s a feature'),
    ('I was stuck in an infinite loop'),
    ('My code compiled on the first try, so I had to investigate'),
    ('I was resolving merge conflicts, emotional and otherwise'),
    ('Git said “detached HEAD” and so did I'),
    ('I force-pushed to main and had to leave the country'),
    ('I was waiting for npm install to finish'),
    ('My node_modules folder is heavier than my car'),
    ('I was stuck in Vim and couldn''t exit'),
    ('I was centering a div'),
    ('I was fixing one bug and created three more'),
    ('I was debugging with console.log, it takes time'),
    ('Stack Overflow was down'),
    ('I was waiting for the build to pass'),
    ('The CI pipeline is red and so am I'),
    ('I was explaining my code to a rubber duck'),
    ('I was in a meeting about having fewer meetings'),
    ('I was told it was a five-minute fix'),
    ('I was fighting the cache, the cache won'),
    ('I cleared my cache and my memory with it'),
    ('It was a DNS issue. It''s always DNS'),
    ('My regex worked, I don’t know why, so I stayed to watch it'),
    ('Off-by-one error, I''m actually early'),
    ('My timestamp was in UTC'),
    ('I had a race condition with my alarm clock'),
    ('I got a NullPointerException trying to find my keys'),
    ('I was stuck in a deadlock with my bed'),
    ('My motivation is still loading'),
    ('My brain ran out of memory'),
    ('I''m running on legacy hardware today'),
    ('I need a reboot'),
    ('I tried turning myself off and on again'),
    ('My energy is deprecated'),
    ('I''m in safe mode today'),
    ('My response time is currently degraded'),
    ('I''m waiting on a dependency'),
    ('It''s blocked by another ticket'),
    ('That’s out of scope'),
    ('It''ll be fixed in the next sprint'),
    ('That’s a backend problem'),
    ('That’s a frontend problem'),
    ('Have you tried clearing your cookies?'),
    ('I was reading the documentation, all of it'),
    ('The documentation was out of date'),
    ('I was updating my dependencies and now nothing works'),
    ('The intern deployed on a Friday'),
    ('I was rolling back a Friday deploy'),
    ('Production went down, and I went with it'),
    ('I was waiting for Windows to finish updating, 1 of 47'),
    ('My keyboard layout switched to QWERTZ'),
    ('Caps lock was on'),
    ('My Bluetooth headphones connected to someone else'),
    ('I was on a call but my mic was muted the whole time'),
    ('I was naming a variable'),
    ('I spent an hour on a missing semicolon'),
    ('Tabs vs spaces, we had to settle it'),
    ('I accidentally closed all 87 tabs'),
    ('The VPN disconnected me from reality'),
    ('My password needed a special character, so did my patience'),
    ('I was solving a captcha, I''m apparently not human'),
    ('My two-factor code expired while I typed it'),
    ('I was writing tests, they all failed, including me'),
    ('It passed all the tests, which is suspicious'),
    ('Legacy code, written by me, last year'),
    ('I was refactoring, I’ll be done never'),
    ('I was estimating the task, it took longer than the task'),
    ('I''m 90% done, the other 90% is next'),
    ('The cloud was cloudy'),
    ('Our server is in another time zone'),
    ('Low battery, low patience'),
    ('I''m not late, I''m asynchronous'),
    ('I''m eventually consistent'),
    ('I was garbage collected'),
    ('Task failed successfully'),
    ('sudo let me be late'),
    ('Permission denied'),
    ('Error 418: I''m a teapot'),
    ('Error 503: service unavailable, try again later'),
    ('Error 429: too many requests, slow down'),
    ('A pigeon stole my train ticket'),
    ('I was abducted by aliens, they said hi'),
    ('I got stuck in a revolving door for an hour'),
    ('A goose chased me for three streets'),
    ('I accidentally joined a marathon'),
    ('I was mistaken for a celebrity and had to sign autographs'),
    ('My GPS took me to Belgium'),
    ('I fell into a time loop, this is my fourth attempt'),
    ('A mime trapped me in an invisible box'),
    ('I was busy winning an argument with my reflection'),
    ('My horoscope told me to stay in bed'),
    ('Mercury is in retrograde'),
    ('A psychic told me today was dangerous'),
    ('My goldfish needed emotional support'),
    ('My cat locked me in the bathroom'),
    ('My dog hid my car keys on purpose'),
    ('A raccoon took my sandwich and I followed him'),
    ('I was helping a duck cross the road with her ducklings, all twelve of them'),
    ('My parrot told everyone I’d left already'),
    ('My hamster escaped and joined a gang'),
    ('I got lost in IKEA'),
    ('I was stuck behind a parade I didn''t know about'),
    ('I accidentally got on a boat'),
    ('My bus was hijacked by a group of grandmas'),
    ('I was trapped in a conversation with a stranger about his boat'),
    ('A tourist asked me for directions and I went with them'),
    ('I was chosen for a street magic trick and couldn''t leave'),
    ('I was an extra in a film being shot on my street'),
    ('I was a witness to a very minor crime'),
    ('I was kidnapped by my own nap'),
    ('My shadow ran off and I had to catch it'),
    ('My left shoe went to work without me'),
    ('Gravity was stronger on my side of town'),
    ('Time works differently in my flat'),
    ('My clock runs on French time, the slow version'),
    ('I was busy saving the world, you’re welcome'),
    ('I was in a secret meeting I''m not allowed to talk about'),
    ('My evil twin took my place, the one who came on time was him'),
    ('I had to return a library book from 2009'),
    ('I was stuck in a staring contest with a cat'),
    ('A bee wouldn’t let me leave the house'),
    ('There was a spider in my shoe and we had to negotiate'),
    ('I had to wait for my toast to cool down'),
    ('My coffee told me to slow down'),
    ('I was trying to fold a fitted sheet'),
    ('I was looking for the end of the sellotape'),
    ('I got trapped under a very comfortable blanket'),
    ('I was reading the terms and conditions'),
    ('My Wi-Fi password was in the other house'),
    ('I was practising my apology for being late'),
    ('I was trying to remember if I’d already eaten'),
    ('I put my clothes on inside out, twice'),
    ('I was untangling my headphones'),
    ('I got stuck in my jumper'),
    ('My zip broke and I had to rethink my outfit'),
    ('The neighbour’s cat sat on my car and I didn''t have the heart'),
    ('I got distracted by a really good cloud'),
    ('I stopped to smell the roses, all of them'),
    ('A seagull took my croissant and my motivation'),
    ('I was in a queue that turned out to be for nothing'),
    ('I joined the wrong Zoom call and stayed out of politeness'),
    ('I accidentally booked a flight'),
    ('I fell asleep in the shower'),
    ('I was trapped in a group chat'),
    ('The universe was testing my patience, I passed'),
    ('I was told to wait by a sign'),
    ('My car only turns left today'),
    ('My alarm clock went on strike'),
    ('I dreamt I was already here'),
    ('I was early, then I wasn''t'),
    ('I left on time, it just didn''t work out'),
    ('My ancestors told me to wait'),
    ('I was meditating and reached a higher plane, and missed the bus'),
    ('A fortune cookie said not today'),
    ('My plants staged an intervention'),
    ('I was stuck in traffic, on foot'),
    ('I took a shortcut'),
    ('I was having an existential crisis, it''s sorted now'),
    ('I''m here, you’re just seeing an old version of me'),
    ('I was never late, you were early');